[32m2024-07-17 15:03:23 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e12f2a9f-e59b-44b5-a946-8e3363a20836 - 8014 - LOGS_CAPTURED - Started capturing logs in process (pid: 8014).
[32m2024-07-17 15:03:23 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e12f2a9f-e59b-44b5-a946-8e3363a20836 - 8014 - taxi_zones - STEP_START - Started execution of step "taxi_zones".
[32m2024-07-17 15:03:23 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - e12f2a9f-e59b-44b5-a946-8e3363a20836 - 8014 - taxi_zones - STEP_FAILURE - Execution of step "taxi_zones" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_zones"::

duckdb.duckdb.ParserException: Parser Error: syntax error at or near "zone_id"

Stack Trace:
  File "/Users/akiwacky/Desktop/Projects/dagster_starter/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/akiwacky/Desktop/Projects/dagster_starter/venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/akiwacky/Desktop/Projects/dagster_starter/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/akiwacky/Desktop/Projects/dagster_starter/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/akiwacky/Desktop/Projects/dagster_starter/dagster_university/dagster_university/assets/trips.py", line 72, in taxi_zones
    conn.execute(sql_query)
[0m
